language: node_js
node_js:
  - '14.17.4'
cache: npm
services:
  - docker
stages:
  - name: ESLint, Prettier, Unit tests, Integration tests, Detect Secrets
  - name: Detect Secrets
  - name: Build & Push
    if: branch IN (replace-with-branches) AND type = push AND fork = false
jobs:
  include:
    - stage: ESLint, Prettier, Unit tests, Integration tests, Detect Secrets
      env: NAME=ESLint & Prettier
      script:
        - npm run lint && npm run prettier:verify
    - env: NAME=Unit and Integration tests
      script:
        - npm run test:coverage
    - env: NAME=Detect Secrets
      script: npm run detect-secrets || git --no-pager diff
    - stage: Build & Push
      script:
        - bash ./scripts/build-and-save.sh
      skip_cleanup: true
env:
  global:
    # SECURE_IBMCLOUD_APIKEY
    - secure: TODO
    # DOCKERHUB_USERNAME
    - secure: TODO
    # DOCKERHUB_PASSWORD
    - secure: TODO
