# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.ibm.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  eslint-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.16.0
        uses: actions/checkout@master
      - run: npm ci
      - run: npm run lint:verify

  prettier-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.16.0
        uses: actions/checkout@master
      - run: npm ci
      - run: npm run prettier:verify

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.16.0
        uses: actions/checkout@master
      - run: npm ci
      - run: npm run detect-secrets $(git ls-files)

  snyk_test:
    runs-on: ubuntu-latest
    needs: [commitlint, eslint-verify, prettier-verify, detect-secrets]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.16.0
        uses: snyk/actions/node@master
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://{{cookiecutter.github_url}}/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

  test:
    runs-on: ubuntu-latest
    needs: [commitlint, eslint-verify, prettier-verify, detect-secrets]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@master
        with:
          node-version: 18.16.0
      - run: touch .env
      - run: npm ci
      - run: npm test
      # - run: npx sonar-scanner
